/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universidad.visita;

import javax.swing.JOptionPane;
import universidad.AccesoADatos.MateriaData;
import universidad.Entidades.Materia;

/**
 *
 * @author Mila
 */
public class VistaMateria extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaMateria
     */
    
    MateriaData md;
    Materia materia = null;
    
    public VistaMateria() {
        initComponents();
        md = new MateriaData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfCodigo = new javax.swing.JTextField();
        tfAño = new javax.swing.JTextField();
        tfNombre = new javax.swing.JTextField();
        NuevoMateria = new javax.swing.JButton();
        EliminarMateria = new javax.swing.JButton();
        GuardarMateria = new javax.swing.JButton();
        SalirMateria = new javax.swing.JButton();
        BuscarMateria = new javax.swing.JButton();
        EstadoActivo = new javax.swing.JRadioButton();
        EstadoInactivo = new javax.swing.JRadioButton();

        setPreferredSize(new java.awt.Dimension(479, 412));
        setRequestFocusEnabled(false);

        jPanel1.setBackground(new java.awt.Color(68, 167, 132));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Codigo(id)");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Materia");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Nombre");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Estado");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("Año");

        NuevoMateria.setText("Nuevo");
        NuevoMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoMateriaActionPerformed(evt);
            }
        });

        EliminarMateria.setText("Eliminar");
        EliminarMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarMateriaActionPerformed(evt);
            }
        });

        GuardarMateria.setText("Guardar");
        GuardarMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarMateriaActionPerformed(evt);
            }
        });

        SalirMateria.setText("Salir");
        SalirMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirMateriaActionPerformed(evt);
            }
        });

        BuscarMateria.setText("Buscar");
        BuscarMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarMateriaActionPerformed(evt);
            }
        });

        buttonGroup1.add(EstadoActivo);
        EstadoActivo.setText("Activo");

        buttonGroup1.add(EstadoInactivo);
        EstadoInactivo.setText("Inactivo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1))
                                .addGap(70, 70, 70)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(68, 68, 68)
                                        .addComponent(BuscarMateria))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(EstadoActivo)
                                        .addGap(18, 18, 18)
                                        .addComponent(EstadoInactivo))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(tfAño, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                        .addComponent(tfNombre, javax.swing.GroupLayout.Alignment.LEADING))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(NuevoMateria)
                                .addGap(28, 28, 28)
                                .addComponent(EliminarMateria)
                                .addGap(28, 28, 28)
                                .addComponent(GuardarMateria)
                                .addGap(32, 32, 32)
                                .addComponent(SalirMateria))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BuscarMateria))
                        .addGap(18, 18, 18)
                        .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(EstadoActivo)
                    .addComponent(EstadoInactivo))
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NuevoMateria)
                    .addComponent(EliminarMateria)
                    .addComponent(GuardarMateria)
                    .addComponent(SalirMateria))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GuardarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarMateriaActionPerformed
        // TODO add your handling code here:
        
            if (materia == null) {
                
                if (!chequeo()) {
                    int codigo = Integer.parseInt(tfCodigo.getText());
                    String nombre = tfNombre.getText();
                    int Año = Integer.parseInt(tfAño.getText());

                    boolean seleccionado = false;
                    if (EstadoActivo.isSelected()) {
                    seleccionado = true;
                    Materia materiaa = new Materia(codigo, nombre, Año, seleccionado);
                    md.GuardarMateria(materiaa);
                    } else if (!EstadoActivo.isSelected() && !EstadoInactivo.isSelected()) {
                    JOptionPane.showMessageDialog(this, "Porfavor Seleccione un Estado", "Error", JOptionPane.WARNING_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Por favor complete los campos obligatorios ", "Atencion!", JOptionPane.WARNING_MESSAGE);

                }
                
            } else {
                
                int codigo = Integer.parseInt(tfCodigo.getText());
                String nombre = tfNombre.getText();
                int Año = Integer.parseInt(tfAño.getText());
                boolean seleccionado = false;
                    if (EstadoActivo.isSelected()) {
                    seleccionado = true;
                    }
                
                materia = new Materia (codigo, nombre, Año, seleccionado);
                
                md.modificarMateria(materia);
            }   
    }//GEN-LAST:event_GuardarMateriaActionPerformed

    private void SalirMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirMateriaActionPerformed
        // TODO add your handling code here:
        
        int repuesta = JOptionPane.showConfirmDialog(this, "Esta seguro de Salir ?", "Atencion", JOptionPane.OK_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE);

        if (repuesta == 0) {
            dispose();
        }
    }//GEN-LAST:event_SalirMateriaActionPerformed

    private void NuevoMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoMateriaActionPerformed
        // TODO add your handling code here:
        limpiarCampos();
        materia = null;
    }//GEN-LAST:event_NuevoMateriaActionPerformed

    private void BuscarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarMateriaActionPerformed
        // TODO add your handling code here:
        
        if (!tfCodigo.getText().isEmpty()) {
            int Codigo = Integer.parseInt(tfCodigo.getText());
            materia = md.buscarMateria(Codigo);

            if (materia != null) {
                tfAño.setText(materia.getAnioMateria() + "");
                tfNombre.setText(materia.getNombre());

                if (materia.isActivo()) {
                    EstadoActivo.setSelected(true);
                } else {
                    EstadoInactivo.setSelected(true);
                }
            }

        } else {
            JOptionPane.showMessageDialog(this, "Introduzca un codigo para buscar", "Campo Vacio", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_BuscarMateriaActionPerformed

    private void EliminarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarMateriaActionPerformed
        // TODO add your handling code here:
        
        if (!tfCodigo.getText().isEmpty()) {
            int codigo = Integer.parseInt(tfCodigo.getText());
            
            md.eliminarMateria(codigo);
            limpiarCampos();
            materia = null;
        }
        
    }//GEN-LAST:event_EliminarMateriaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuscarMateria;
    private javax.swing.JButton EliminarMateria;
    private javax.swing.JRadioButton EstadoActivo;
    private javax.swing.JRadioButton EstadoInactivo;
    private javax.swing.JButton GuardarMateria;
    private javax.swing.JButton NuevoMateria;
    private javax.swing.JButton SalirMateria;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField tfAño;
    private javax.swing.JTextField tfCodigo;
    private javax.swing.JTextField tfNombre;
    // End of variables declaration//GEN-END:variables

    public boolean chequeo() {

        return (tfCodigo.getText().isEmpty() || tfNombre.getText().isEmpty() || tfAño.getText().isEmpty());
    }

    public void limpiarCampos() {
        tfAño.setText("");
        tfCodigo.setText("");
        tfNombre.setText("");
        EstadoActivo.setSelected(false);
        EstadoInactivo.setSelected(false);
    }
    
}
